# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-05-28 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departamentos',
            new_name='Departamento',
        ),
        migrations.RenameModel(
            old_name='Municipios',
            new_name='Municipio',
        ),
        migrations.RenameModel(
            old_name='Tdocumentos',
            new_name='Tdocumento',
        ),
    ]
