# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20160528_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='departamento',
            name='estregistro',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
    ]
