# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20170510_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRelacionFamiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estregistro', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='tdocumento',
            name='estadoregistro',
        ),
        migrations.AddField(
            model_name='tdocumento',
            name='estregistro',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tdocumento',
            name='sigla',
            field=models.CharField(max_length=8),
        ),
    ]
