# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_auto_20170510_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estregistro',
        ),
        migrations.AlterUniqueTogether(
            name='municipios',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='municipios',
            name='departamento',
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tdocumento',
        ),
        migrations.DeleteModel(
            name='TEtnias',
        ),
        migrations.DeleteModel(
            name='TRelacionFamiliar',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Municipios',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Tdocumento',
        ),
    ]
