# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 04:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0017_niveles'),
        ('establecimiento', '0003_auto_20170512_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimientos',
            name='correoelectronico',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Correo electronico'),
        ),
        migrations.AddField(
            model_name='establecimientos',
            name='fechafundacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de fundacion'),
        ),
        migrations.AddField(
            model_name='establecimientos',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='Municipio', to='configuracion.Municipios'),
        ),
        migrations.AddField(
            model_name='establecimientos',
            name='nombreRector',
            field=models.CharField(default='Rector de prueba', max_length=200),
        ),
        migrations.AddField(
            model_name='establecimientos',
            name='numsedes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='establecimientos',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='establecimientos',
            name='tieneMatriculaContrada',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, verbose_name='tiene matricula contratada'),
        ),
        migrations.AlterField(
            model_name='establecimientos',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='establecimientos',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
