# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0005_establecimientos_escudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimientos',
            name='numsedes',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
