# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 01:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0006_auto_20170530_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('direccion', models.CharField(blank=True, max_length=100, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('responsable', models.CharField(default='Rector de prueba', max_length=200)),
                ('estregistro', models.IntegerField(default=1)),
                ('establecimiento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='Establecimiento', to='establecimiento.Establecimientos')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sedes',
            unique_together=set([('establecimiento', 'codigo')]),
        ),
    ]
