# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0007_auto_20170531_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimientos',
            name='direccion',
        ),
    ]
