# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0008_remove_establecimientos_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimientos',
            name='correoelectronico',
        ),
        migrations.RemoveField(
            model_name='establecimientos',
            name='telefono',
        ),
        migrations.AddField(
            model_name='sedes',
            name='correoelectronico',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Correo electronico'),
        ),
    ]
