# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0022_auto_20170529_2218'),
        ('establecimiento', '0009_auto_20170531_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estregistro', models.IntegerField(default=1)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='Tjornada', to='configuracion.Tjornada')),
            ],
        ),
        migrations.AlterField(
            model_name='sedes',
            name='responsable',
            field=models.CharField(default='Persona prueba', max_length=200),
        ),
        migrations.AddField(
            model_name='jornadas',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='Sede', to='establecimiento.Sedes'),
        ),
        migrations.AlterUniqueTogether(
            name='jornadas',
            unique_together=set([('sede', 'jornada')]),
        ),
    ]
