# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-17 19:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0024_auto_20170610_0942'),
        ('establecimiento', '0012_auto_20170617_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivelesaprobados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroActo', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)])),
                ('anexo', models.ImageField(upload_to='institucional/actosadmin/')),
                ('fecha', models.DateField(blank=True, default='2006-05-04', verbose_name='Fecha del acto administrativo')),
                ('estregistro', models.IntegerField(default=1)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimiento.Establecimientos')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Niveles')),
                ('tipoaprobacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Tactoadmin')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='nivelesaprobados',
            unique_together=set([('nivel', 'establecimiento')]),
        ),
    ]
