# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-17 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0013_auto_20170617_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelesaprobados',
            name='fecha',
            field=models.DateField(blank=True, verbose_name='Fecha del acto administrativo'),
        ),
    ]
