# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-17 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0014_auto_20170617_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelesaprobados',
            name='anexo',
            field=models.FileField(upload_to='institucional/actosadmin/'),
        ),
    ]
