# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=2)),
                ('nombre', models.CharField(max_length=10)),
                ('estregistro', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Estregistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='normal', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(error_messages={'invalid': 'Ingreseeeeee un valor valido', 'required': 'Esteeeeeee campo es requerido.'}, max_length=3)),
                ('nombre', models.CharField(max_length=50)),
                ('estregistro', models.IntegerField(default=1)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='Departamento', to='configuracion.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(error_messages={'invalid': 'Ingreseeeeee un valor valido', 'required': 'Esteeeeeee campo es requerido.'}, max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('numerodocumento', models.CharField(max_length=30, verbose_name='Numero de documento')),
                ('direccion', models.CharField(blank=True, max_length=100, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('fechanacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('correoelectronico', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Genero de nacimiento')),
                ('estregistro', models.IntegerField(default=1)),
                ('foto', models.ImageField(blank=True, default='fotos/personas/avatars_mini.png', upload_to='fotos/personas/')),
            ],
        ),
        migrations.CreateModel(
            name='Tdocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=8)),
                ('estregistro', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TEtnias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=8)),
                ('estregistro', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TRelacionFamiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estregistro', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='tdocumento',
            field=models.ForeignKey(error_messages={'required': 'Please choose a star rating'}, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Tdocumento', verbose_name='Tipo de documento'),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together=set([('nombres', 'apellidos', 'numerodocumento')]),
        ),
        migrations.AlterUniqueTogether(
            name='municipios',
            unique_together=set([('codigo', 'departamento')]),
        ),
    ]
