# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=2, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together=set([('codigo', 'nombre')]),
        ),
    ]
