# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_auto_20170510_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
