# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20170510_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('estregistro', models.IntegerField(default=1)),
            ],
            options={
                'default_related_name': 'metodologia',
            },
        ),
    ]
