# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_metodologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=40)),
                ('estregistro', models.IntegerField(default=1)),
            ],
            options={
                'default_related_name': 'especialidad',
            },
        ),
        migrations.AlterField(
            model_name='metodologia',
            name='codigo',
            field=models.CharField(max_length=2),
        ),
    ]
