# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_auto_20170516_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodologia',
            name='codigo',
            field=models.CharField(error_messages={'unique': 'This email has already been registered.'}, max_length=2, unique=True),
        ),
    ]
