# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-20 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0013_caracter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracter',
            name='nombre',
            field=models.CharField(error_messages={'invalid': 'El valor ingresado no es valido', 'required': 'Este campo es requerido.', 'unique': 'Ya se encuentra registrado en el sistema.'}, max_length=200, unique=True),
        ),
    ]
