# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-20 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0014_auto_20170520_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caracter',
            new_name='Tcaracter',
        ),
    ]
