# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 05:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0017_niveles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(error_messages={'invalid': 'El valor ingresado no es valido', 'required': 'Este campo es requerido.', 'unique': 'Ya se encuentra registrado en el sistema.'}, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('nombre', models.CharField(error_messages={'invalid': 'El valor ingresado no es valido', 'required': 'Este campo es requerido.', 'unique': 'Ya se encuentra registrado en el sistema.'}, max_length=200, unique=True)),
                ('estregistro', models.IntegerField(default=1)),
            ],
            options={
                'default_related_name': 'Niveles',
            },
        ),
    ]
