# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 05:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0018_grados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grados',
            name='codigo',
            field=models.IntegerField(error_messages={'invalid': 'El valor ingresado no es valido', 'required': 'Este campo es requerido.', 'unique': 'Ya se encuentra registrado en el sistema.'}, unique=True, validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
