# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0023_tactoadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tactoadmin',
            name='aplicacion',
            field=models.CharField(error_messages={'invalid': 'El valor ingresado no es valido', 'required': 'Este campo es requerido.', 'unique': 'Ya se encuentra registrado en el sistema.'}, max_length=3),
        ),
    ]
